name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            echo "Connected user:"
            whoami

            echo "Going to project directory:"
            cd /var/www/git-cicd-lab

            echo "Current directory:"
            pwd

            echo "Current branch:"
            git branch --show-current

            echo "Commit before pull:"
            git log -1 --oneline

            echo "Pulling latest changes:"
            git pull origin main

            echo "Commit after pull:"
            git log -1 --oneline

            echo "Deployment completed."